blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path(
        '<int:year>/<int:month>/<int:day>/<str:slug>/',
        views.post_detail,
        name='post_detail'
    ),
    path('tag/<str:tag_slug>/',
        views.post_list, name='post_list_by_tag'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('wiki/', include('wiki.urls', namespace='wiki'))
]

wiki/urls.py
from django.urls import path

from . import views

app_name = 'wiki'
urlpatterns = [
    # wiki
    path('', views.wiki_home, name='wiki_host'),
]

blog/models.py
from hashlib import md5

from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from taggit.managers import TaggableManager


class Post(models.Model):

    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10,
        choices=STATUS_CHOICES,
        default='draft')
    tags = TaggableManager()

    class Meta:
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_url(self):
        return reverse(
            'blog:post_detail',
            args=[
                self.publish.year,
                self.publish.month,
                self.publish.day,
                self.slug
            ]
        )


class Comment(models.Model):

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments')
    username = models.CharField(max_length=120)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.username, self.post)

    def avatar(self, size=60):
        md5_digest = md5(self.email.lower().encode('utf-8')).hexdigest()
        return 'https://www.gravatar.com/avatar/{}?d=identicon&s={}'.format(
            md5_digest, size)

wiki/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = ('username', 'email', 'body')

blog/views.py
from django.shortcuts import render
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from taggit.models import Tag

from .models import Post, Comment
from .forms import CommentForm


def post_list(request, tag_slug=None):
    if tag_slug:
        tag = Tag.objects.filter(slug=tag_slug).first()
        post_list = Post.objects.filter(tags__in=[tag])
    else:
        post_list = Post.objects.all()
    tag_list = Tag.objects.all()
    paginator = Paginator(post_list, 3)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(
        request,
        'blog/post/list.html',
        {'posts': posts, 'tag_list': tag_list}
    )


def post_detail(request, year, month, day, slug):
    post = Post.objects.filter(
        publish__year=year,
        publish__month=month,
        publish__day=day,
        slug=slug
    ).first()
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    tag_list = Tag.objects.all()
    return render(
        request,
        'blog/post/detail.html',
        {
            'post': post,
            'comments': comments,
            'new_comment': new_comment,
            'comment_form': comment_form,
            'tag_list': tag_list
        }
    )

wiki/views.py
from django.shortcuts import render

# Create your views here.


def wiki_home(request):
    return render(request, 'index.html')

blog/templates/blog/base.html
<html>

{% load static %}

<head>
    <title>
        pengxiao.io
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Bootstrap -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/prettify.css' %}" type="text/css" rel="stylesheet" />
    <link href="{% static 'css/colorbox.css' %}" rel="stylesheet" type="text/css" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" type="text/css" />
</head>

<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="/blog">pengxiao.io</a>
                </div>
                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                    <ul class="nav navbar-nav">
                        <li><a href="/blog/">Home</a></li>
                        <li><a href="/blog/about-me">About Me</a></li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li>
                            <p class="navbar-text" style="margin-top: 10px; margin-bottom: 0px;">
                                <a href="http://github.com/xiaopeng163"><img src="{% static 'picture/github.png' %}"
                                        alt="GitHub" title="GitHub" /></a>
                                <a href="https://twitter.com/xiaopeng163"><img src="{% static 'picture/twitter.png' %}"
                                        alt="Twitter" title="Twitter" /></a>
                            </p>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                <div id="main">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
            <div class="col-md-4 sidebar-bg">
                <div id="sidebar">

                    <h1>About Peng Xiao</h1>
                    <img style="float: right; margin: 0px 8px 8px 0px; padding: 4px; border: 1px solid #ccc;"
                        src="{% static 'picture/pengxiao.jpg' %}" />
                    <p>Welcome to my blog!</p>
                    <p>I'm a Network DevOps Engineer, Online instructor, currently living in The Hague, Netherlands.</p>

                    <p>You can also find me on <a href="https://github.com/xiaopeng163">Github</a> and <a
                            href="https://twitter.com/xiaopeng163">Twitter</a>.</p>
                    <p>Thank you for visiting!</p>
                    <h1>Tags</h1>
                    <ul>
                        {% for tag in tag_list %}
                        <li>
                            <span class="label label-primary"><a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a></span>
                            ({{ tag.taggit_taggeditem_items.count }})</li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
        </div>
        <div id="footer">
            <p>&copy; 2018-
                <script type="text/javascript">document.write(new Date().getFullYear());</script> by Peng Xiao. All
                rights reserved. <a href="mailto:xiaoquwl _at_ gmail _dot_ com">Questions?</a></p>
        </div>
    </div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.colorbox-min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/prettify.js' %}"></script>
    <script src="{% static 'js/moment-with-langs.min.js' %}"></script>
    <script>
        function flask_moment_render(elem) {
            $(elem).text(eval('moment("' + $(elem).data('timestamp') + '").' + $(elem).data('format') + ';'));
            $(elem).removeClass('flask-moment');
        }
        function flask_moment_render_all() {
            $('.flask-moment').each(function () {
                flask_moment_render(this);
                if ($(this).data('refresh')) {
                    (function (elem, interval) { setInterval(function () { flask_moment_render(elem) }, interval); })(this, $(this).data('refresh'));
                }
            })
        }
        $(document).ready(function () {
            flask_moment_render_all();
        });
    </script>
    <script type="text/javascript">
        $(document).ready(function () {
            $(".gallery").colorbox({ rel: ".gallery", maxWidth: "95%", maxHeight: "95%", scalePhotos: true });
            // add prettyprint class to all <pre><code></code></pre> blocks
            var prettify = false;
            $("pre code").parent().each(function () {
                $(this).addClass('prettyprint');
                prettify = true;
            });
            prettyPrint();
        });
    </script>

</body>

</html>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block content %}

<div class="post">
    <p class="date"><span class="flask-moment" data-timestamp="{{ post.publish }}" data-format="format('LL')"
            data-refresh="0">{{ post.publish }}</span></p>
    <h1 class="post-title"><a href="{{ post.get_url }}">{{ post.title }}</a></h1>
    <div class="posted">Posted by <span class="label label-danger">{{ post.author }}</span>
        {% if post.tags.count %}
        tags
        {% for tag in post.tags.all %}
        <span class="label label-primary"><a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a></span>
        {% if not forloop.last %}, {% endif %}
        {% endfor %}
        {% endif %}
    </div>
    <div class="post_body">
        <p>{{ post.body|linebreaks }}</p>
    </div>


    <!-- <h2>Similar posts</h2>
    {% for post in post.tags.similar_objects %}
    <p>
        <a href="{{ post.get_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    There are no similar posts yet.
    {% endfor %}
    <hr> -->
    {% with comments.count as total_comments %}
    <h4 style="text-align: right"><a name="comments"></a> {{ total_comments }} comment{{ total_comments|pluralize }}
    </h4>
    {% endwith %}
    <div class="comment">
        <ul>
            {% for comment in comments %}
            <li>
                <div class="comment-thumbnail"><img
                        src="{{ comment.avatar }}" /></div>
                <div class="comment-body">
                    <p>
                        <span class="label label-default">#{{ forloop.counter }}</span> <span class="label label-primary">{{ comment.username }}</span> said
                        <span class="flask-moment">{{ comment.created }}</span>
                    </p>
                    <div style="overflow: auto;">
                        <p style="white-space: pre-wrap;"> {{ comment.body }}</p>
                    </div>
                </div>
            </li> 
            {% empty %}
            <p>There are no comments yet.</p>
            {% endfor %}
        </ul>


        {% if new_comment %}
        <h2>Your comment has been added.</h2>
        {% else %}
        <h3><a name="commentform"></a>Leave a Comment</h3>
        <form action="#commentform" method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
        {% endif %}

    </div>
</div>
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block content %}

{% for post in posts %}
<div class="post">
  <p class="date"><span class="flask-moment">{{ post.publish }}</span></p>
  <h1 class="post-title"><a href="{{ post.get_url }}">{{ post.title }}</a></h1>

  <div class="posted">Posted by <span class="label label-danger"><a href="/author/pengxiao">{{ post.author }}</a></span>
    {% if post.tags.count %}
    tags
    {% for tag in post.tags.all %}
    <span class="label label-primary"><a href="{% url "blog:post_list_by_tag" tag.slug %}">{{ tag.name }}</a></span>
    {% if not forloop.last %}, {% endif %}
    {% endfor %}
    {% endif %}
  </div>
  <div class="post_body">
    <p> {{ post.body|truncatewords:30|linebreaks }}</p>
  </div>
  <div style="clear: both;"><a href="{{ post.get_url }}">Read more...</a>
  </div>
</div>
{% endfor %}

<div class="page">
  <ul class="pager">
    {% if posts.has_previous %}
      <li class="previous">
        <a href="?page={{ posts.previous_page_number }}"> &larr; Newer Posts</a>
      </li>
    {% else %}
      <li class="previous disabled">
        <a href="#">&larr; Newer Posts</a>
      </li>
    {% endif %}
    {% if posts.has_next %}
      <li class="next">
        <a href="?page={{ posts.next_page_number }}">Older Posts &rarr;</a>
      </li>
    {% else %}
      <li class="next disabled">
        <a href="#">Older Posts &rarr;</a>
      </li>
    {% endif %}    
  </ul>
</div>

{% endblock %}

wiki/templates/index.html
<html>
    <h1>敬请期待!!!!!!!!!</h1>
</html>